---

## Effect that I am going for
vm_type:
- alias: default
  default: m3.medium

## Stupid attempt to make that happen
- type: replace
  path: /vm_type?/-
  value: |
    alias: default
    default: m3.medium

# define persistent disk size
- type: replace
  path: /instance_groups/name=mysql/persistent_disk_type
  value: 50GB

# specify my AZ names
- type: replace
  path: /instance_groups/name=mysql/azs
  value: [z1, z2, z3]

# override the network name 'default' to BBL-supplied, 'private'
- type: replace
  path: /instance_groups/name=mysql/networks/name=default
  value: private
- type: replace
  path: /instance_groups/name=arbitrator/networks/name=default
  value: private
- type: replace
  path: /instance_groups/name=proxy/networks/name=default
  value: private
- type: replace
  path: /instance_groups/name=bootstrap/networks/name=default
  value: private
- type: replace
  path: /instance_groups/name=rejoin-unsafe/networks/name=default
  value: private
- type: replace
  path: /instance_groups/name=verify-cluster-schemas/networks/name=default
  value: private
- type: replace
  path: /instance_groups/name=smoke-tests/networks/name=default
  value: private
